version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    working_dir: /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: laravel-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: